import * as React from "react";
import {
  DataGrid,
  GridToolbarContainer,
  GridToolbarExport,
} from "@mui/x-data-grid";
import { Stack, Box } from "@mui/material";

function CustomToolbar() {
  return (
    <Stack direction="row-reverse">
      <GridToolbarContainer>
        <GridToolbarExport printOptions={{ disableToolbarButton: true }} />
      </GridToolbarContainer>
    </Stack>
  );
}


const columns = [
  {
    field: "id",
    headerName: "ID",
    flex: 1
  },
  { field: "firstName", headerName: "First Name" },
  { field: "lastName", headerName: "Last Name" },
  {
    field: "age",
    headerName: "Age",
    flex: 1,
    //type: "number"
  },
  {
    field: "fullName",
    headerName: "Full Name",
    description: "This column has a value getter and is not sortable.",
    sortable: false,
    valueGetter: (params) =>
      `${params.row.firstName || ""} ${params.row.lastName || ""}`,
    minWidth: 100,
  },
  { field: "employeeId", headerName: "Employee ID" },
  { field: "email", headerName: "Email" },
  { field: "mobile", headerName: "Mobile" },
  { field: "hireDate", headerName: "Hire Date" },
  { field: "jobId", headerName: "Job ID" },
  { field: "salary", headerName: "Salary" },
  { field: "commisionPercentage", headerName: "Comm Pct" },
  { field: "managerId", headerName: "Manager ID" },
  { field: "departmentId", headerName: "Department ID" },
  { field: "alternateEmail", headerName: "Alt Email" },
  { field: "alternateMobile", headerName: "Alt Mobile" },
  { field: "city", headerName: "City" },
  { field: "area", headerName: "Area" },
  { field: "district", headerName: "District" },
  { field: "subDistrict", headerName: "Sub District" },
  { field: "state", headerName: "State" },
  { field: "pinCode", headerName: "Pin Code" },
  { field: "country", headerName: "Country" },
  { field: "gender", headerName: "Gender" },
  { field: "maritalStatus", headerName: "Marital Status" },
];

const rows = [
  {
    id: 1,
    firstName: "John",
    lastName: "De",
    age: 35,
    employeeId: "01",
    email: "john@gmail.com",
    mobile: 8565894789,
    hireDate: "12/01/2021",
    jobId: 789,
    salary: 74000,
    commisionPercentage: "10%",
    managerId: "07",
    departmentId: 1,
    alternateEmail: "john789@yahoo.com",
    alternateMobile: 7877526589,
    city: "Pune",
    area: "Wakad",
    district: "Pune",
    subDistrict: "Pune",
    state: "Maharashtra",
    pinCode: "411057",
    country: "India",
    gender: "Male",
    maritalStatus: "Single",
  },
  {
    id: 2,
    firstName: "Marry",
    lastName: "Jena",
    age: 25,
    employeeId: "02",
    email: "marry@gmail.com",
    mobile: 8865694745,
    hireDate: "13/01/2021",
    jobId: 788,
    salary: 45000,
    commisionPercentage: "10%",
    managerId: "07",
    departmentId: 1,
    alternateEmail: "jena@yahoo.com",
    alternateMobile: 447752654,
    city: "Pune",
    area: "Aundh",
    district: "Pune",
    subDistrict: "Pune",
    state: "Maharashtra",
    pinCode: "411055",
    country: "India",
    gender: "Female",
    maritalStatus: "Married",
  },
  {
    id: 3,
    firstName: "Nilesh",
    lastName: "Shinde",
    age: 24,
    employeeId: "03",
    email: "nilesh@gmail.com",
    mobile: 9465694875,
    hireDate: "15/01/2021",
    jobId: 779,
    salary: 62000,
    commisionPercentage: "7%",
    managerId: "09",
    departmentId: 2,
    alternateEmail: "nilesh@yahoo.com",
    alternateMobile: 857652652,
    city: "Mumbai",
    area: "Chembur",
    district: "Mumbai",
    subDistrict: "Mumbai",
    state: "Maharashtra",
    pinCode: "412078",
    country: "India",
    gender: "Male",
    maritalStatus: "Single",
  },
  {
    id: 4,
    firstName: "Mahesh",
    lastName: "Shinde",
    age: 27,
    employeeId: "04",
    email: "mahesh@gmail.com",
    mobile: 8967856945,
    hireDate: "17/02/2021",
    jobId: 745,
    salary: 41000,
    commisionPercentage: "7%",
    managerId: "09",
    departmentId: 4,
    alternateEmail: "mahesh@yahoo.com",
    alternateMobile: 817252652,
    city: "Mumbai",
    area: "Goregaon",
    district: "Mumbai",
    subDistrict: "Mumbai",
    state: "Maharashtra",
    pinCode: "412079",
    country: "India",
    gender: "Male",
    maritalStatus: "Married",
  },
  {
    id: 5,
    firstName: "Rima",
    lastName: "Jadhav",
    age: 36,
    employeeId: "05",
    email: "reema@gmail.com",
    mobile: 9867854745,
    hireDate: "11/02/2021",
    jobId: 452,
    salary: 81000,
    commisionPercentage: "14%",
    managerId: "10",
    departmentId: 5,
    alternateEmail: "jadhavreema@yahoo.com",
    alternateMobile: 65478956,
    city: "Nagpur",
    area: "Shivaji Nagar",
    district: "Nagpur",
    subDistrict: "Nagpur",
    state: "Maharashtra",
    pinCode: "415689",
    country: "India",
    gender: "Female",
    maritalStatus: "Married",
  },
  {
    id: 6,
    firstName: "Sima",
    lastName: "Kolare",
    age: 20,
    employeeId: "06",
    email: "seema@gmail.com",
    mobile: 9767854745,
    hireDate: "14/02/2021",
    jobId: 452,
    salary: 65000,
    commisionPercentage: "19%",
    managerId: "8",
    departmentId: 6,
    alternateEmail: "seema@yahoo.com",
    alternateMobile: 78478956,
    city: "Nagpur",
    area: "Ramji Nagar",
    district: "Nagpur",
    subDistrict: "Nagpur",
    state: "Maharashtra",
    pinCode: "415691",
    country: "India",
    gender: "Female",
    maritalStatus: "Married",
  },
  {
    id: 7,
    firstName: "Komal",
    lastName: "Patil",
    age: 27,
    employeeId: "07",
    email: "komalpatil@gmail.com",
    mobile: 6698567898,
    hireDate: "13/01/2021",
    jobId: 789,
    salary: 24000,
    commisionPercentage: "6%",
    managerId: "08",
    departmentId: 3,
    alternateEmail: "komalpatil@yahoo.com",
    alternateMobile: 568552654,
    city: "Latur",
    area: "Samarth Nagar",
    district: "Latur",
    subDistrict: "Latur",
    state: "Maharashtra",
    pinCode: "413512",
    country: "India",
    gender: "Female",
    maritalStatus: "Single",
  },
  {
    id: 8,
    firstName: "Piyush",
    lastName: "Nemane",
    age: 29,
    employeeId: "08",
    email: "nemanepiyush@gmail.com",
    mobile: 9292567565,
    hireDate: "2/03/2021",
    jobId: 568,
    salary: 39000,
    commisionPercentage: "8%",
    managerId: "09",
    departmentId: 2,
    alternateEmail: "piyushnemane@yahoo.com",
    alternateMobile: 6789586945,
    city: "Latur",
    area: "Narayan Nagar",
    district: "Latur",
    subDistrict: "Latur",
    state: "Maharashtra",
    pinCode: "413513",
    country: "India",
    gender: "Male",
    maritalStatus: "Married",
  },
  {
    id: 9,
    firstName: "Pramil",
    lastName: "Joshi",
    age: 31,
    employeeId: "09",
    email: "pramil@gmail.com",
    mobile: 7465894721,
    hireDate: "30/03/2022",
    jobId: 456,
    salary: 32500,
    commisionPercentage: "9%",
    managerId: "09",
    departmentId: 5,
    alternateEmail: "pramil568@yahoo.com",
    alternateMobile: 9985658956,
    city: "Satara",
    area: "Khadaki",
    district: "Satara",
    subDistrict: "Satara",
    state: "Maharashtra",
    pinCode: "423562",
    country: "India",
    gender: "Male",
    maritalStatus: "Single",
  },
  {
    id: 10,
    firstName: "Smita",
    lastName: "Kadam",
    age: 23,
    employeeId: "10",
    email: "smita@gmail.com",
    mobile: 9865424745,
    hireDate: "14/04/2022",
    jobId: 113,
    salary: 56000,
    commisionPercentage: "12%",
    managerId: "10",
    departmentId: 3,
    alternateEmail: "smitakadam@yahoo.com",
    alternateMobile: 857725654,
    city: "Kolhapur",
    area: "Swargate",
    district: "Kolhapur",
    subDistrict: "Kolhapur",
    state: "Maharashtra",
    pinCode: "411201",
    country: "India",
    gender: "Female",
    maritalStatus: "Single",
  },
  {
    id: 11,
    firstName: "Suraj",
    lastName: "Londhe",
    age: 28,
    employeeId: "11",
    email: "suraj956@gmail.com",
    mobile: 7565424741,
    hireDate: "6/05/2022",
    jobId: 114,
    salary: 41700,
    commisionPercentage: "4%",
    managerId: "10",
    departmentId: 2,
    alternateEmail: "surajlondhe@yahoo.com",
    alternateMobile: 657120614,
    city: "Amravati",
    area: "Shastri Nagar",
    district: "Amravati",
    subDistrict: "Amravati",
    state: "Maharashtra",
    pinCode: "411205",
    country: "India",
    gender: "Male",
    maritalStatus: "Single",
  },
  {
    id: 12,
    firstName: "Sonal",
    lastName: "Jha",
    age: 26,
    employeeId: "12",
    email: "sonaljha@gmail.com",
    mobile: 5265224739,
    hireDate: "9/05/2022",
    jobId: 115,
    salary: 43500,
    commisionPercentage: "6%",
    managerId: "11",
    departmentId: 7,
    alternateEmail: "sonaljha@yahoo.com",
    alternateMobile: 657120614,
    city: "Amravati",
    area: "Mantri Nagar",
    district: "Amravati",
    subDistrict: "Amravati",
    state: "Maharashtra",
    pinCode: "411205",
    country: "India",
    gender: "Female",
    maritalStatus: "Single",
  },
];

export default function Table() {
  return (
    <div style={{ height: "auto", width: "auto", maxWidth: "100%" }}>
      <DataGrid
        autoHeight={true}
        rowHeight={36}
        rows={rows}
        columns={columns}
        checkboxSelection={true}
        initialState={{
          pagination: {
            paginationModel: { page: 0, pageSize: 4 },
          },
        }}
        pageSizeOptions={[4,8,10]}
        slots={{
          toolbar: CustomToolbar,
        }}
        sx={{
          fontSize:"0.8rem",
          '& .MuiDataGrid-columnHeaderTitle':{
            color:"#262626",fontWeight:"500",fontSize:"0.9rem"
          }
        }}
      />
    </div>
  );
}
